/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tomat' at '17/12/06 23:39' with Gradle 2.14.1
 *
 * @author tomat, @date 17/12/06 23:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
